using Aurora.Domain.Exceptions;
using Aurora.Application.Interfaces;
using Aurora.Domain.Entities;
using Aurora.Domain.Enums;
using MediatR;

namespace Aurora.Application.Features;
public record AccountDto(string Id,string Name,AccountType Type,decimal InitialBalance,decimal CurrentBalance,string Color,bool IsArchived);
public record CategoryDto(string Id,string Name,CategoryType Type,string Color,string Icon,bool IsDefault);
public record TransactionDto(string Id,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes);
public record MonthlySummaryDto(decimal TotalBalance, decimal MonthlyIncome, decimal MonthlyExpense, decimal MonthlyResult, decimal PendingIncome, decimal PendingExpense, int PaidTransactionsCount, int PendingTransactionsCount, List<TransactionDto> RecentTransactions);
public record CategoryExpenseDto(string CategoryId,string CategoryName,string CategoryColor,decimal Total,decimal Percentage);
public record CashFlowItemDto(int Month,decimal Income,decimal Expense,decimal Result);

public record GetAccountsQuery(string UserId): IRequest<List<AccountDto>>;
public record GetAccountByIdQuery(string UserId,string Id): IRequest<AccountDto>;
public record CreateAccountCommand(string UserId,string Name,AccountType Type,decimal InitialBalance,string Color): IRequest<AccountDto>;
public record UpdateAccountCommand(string UserId,string Id,string Name,AccountType Type,decimal InitialBalance,string Color,bool IsArchived): IRequest<AccountDto>;
public record ArchiveAccountCommand(string UserId,string Id): IRequest;
public record DeleteAccountCommand(string UserId,string Id): IRequest;

public record GetCategoriesQuery(string UserId): IRequest<List<CategoryDto>>;
public record CreateCategoryCommand(string UserId,string Name,CategoryType Type,string Color,string Icon): IRequest<CategoryDto>;
public record UpdateCategoryCommand(string UserId,string Id,string Name,CategoryType Type,string Color,string Icon): IRequest<CategoryDto>;
public record DeleteCategoryCommand(string UserId,string Id): IRequest;

public record GetTransactionsQuery(string UserId,int? Month,int? Year,TransactionType? Type,TransactionStatus? Status,string? CategoryId,string? AccountId): IRequest<List<TransactionDto>>;
public record GetTransactionByIdQuery(string UserId,string Id): IRequest<TransactionDto>;
public record CreateTransactionCommand(string UserId,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes): IRequest<TransactionDto>;
public record UpdateTransactionCommand(string UserId,string Id,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes): IRequest<TransactionDto>;
public record DeleteTransactionCommand(string UserId,string Id): IRequest;
public record MarkTransactionAsPaidCommand(string UserId,string Id): IRequest<TransactionDto>;
public record MarkTransactionAsPendingCommand(string UserId,string Id): IRequest<TransactionDto>;

public record GetMonthlySummaryQuery(string UserId,int Month,int Year): IRequest<MonthlySummaryDto>;
public record GetCategoryExpensesQuery(string UserId,int Month,int Year): IRequest<List<CategoryExpenseDto>>;
public record GetCashFlowQuery(string UserId,int Year): IRequest<List<CashFlowItemDto>>;

public static class FinanceMapper {
 public static AccountDto ToDto(this Account x)=>new(x.Id,x.Name,x.Type,x.InitialBalance,x.CurrentBalance,x.Color,x.IsArchived);
 public static CategoryDto ToDto(this Category x)=>new(x.Id,x.Name,x.Type,x.Color,x.Icon,x.IsDefault);
 public static TransactionDto ToDto(this Transaction x)=>new(x.Id,x.AccountId,x.CategoryId,x.Description,x.Amount,x.Type,x.Status,x.Date,x.DueDate,x.Notes);
 public static decimal Impact(TransactionType t, decimal amount)=> t==TransactionType.Income ? amount : -amount;
}

public class GetAccountsHandler(IAccountRepository r):IRequestHandler<GetAccountsQuery,List<AccountDto>>{public async Task<List<AccountDto>> Handle(GetAccountsQuery q,CancellationToken ct)=>(await r.GetByUserAsync(q.UserId)).Select(x=>x.ToDto()).ToList();}
public class GetAccountByIdHandler(IAccountRepository r):IRequestHandler<GetAccountByIdQuery,AccountDto>{public async Task<AccountDto> Handle(GetAccountByIdQuery q,CancellationToken ct)=>(await r.GetByIdAsync(q.Id,q.UserId)??throw new NotFoundException("Conta não encontrada")).ToDto();}
public class CreateAccountHandler(IAccountRepository r):IRequestHandler<CreateAccountCommand,AccountDto>{public async Task<AccountDto> Handle(CreateAccountCommand c,CancellationToken ct){var a=new Account{UserId=c.UserId,Name=c.Name,Type=c.Type,InitialBalance=c.InitialBalance,CurrentBalance=c.InitialBalance,Color=c.Color}; await r.AddAsync(a); return a.ToDto();} }
public class UpdateAccountHandler(IAccountRepository r):IRequestHandler<UpdateAccountCommand,AccountDto>{public async Task<AccountDto> Handle(UpdateAccountCommand c,CancellationToken ct){var a=await r.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Conta não encontrada"); a.Name=c.Name;a.Type=c.Type;a.Color=c.Color;a.IsArchived=c.IsArchived; await r.UpdateAsync(a); return a.ToDto();}}
public class ArchiveAccountHandler(IAccountRepository r):IRequestHandler<ArchiveAccountCommand>{public async Task Handle(ArchiveAccountCommand c,CancellationToken ct){var a=await r.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Conta não encontrada"); a.IsArchived=true; await r.UpdateAsync(a);}}
public class DeleteAccountHandler(IAccountRepository r,ITransactionRepository tr):IRequestHandler<DeleteAccountCommand>{public async Task Handle(DeleteAccountCommand c,CancellationToken ct){if(await tr.ExistsByAccountIdAsync(c.Id,c.UserId)) throw new ConflictException("Conta possui transações vinculadas"); await r.DeleteAsync(c.Id,c.UserId);}}

public class GetCategoriesHandler(ICategoryRepository r):IRequestHandler<GetCategoriesQuery,List<CategoryDto>>{public async Task<List<CategoryDto>> Handle(GetCategoriesQuery q,CancellationToken ct)=>(await r.GetByUserAsync(q.UserId)).Select(x=>x.ToDto()).ToList();}
public class CreateCategoryHandler(ICategoryRepository r):IRequestHandler<CreateCategoryCommand,CategoryDto>{public async Task<CategoryDto> Handle(CreateCategoryCommand c,CancellationToken ct){var x=new Category{UserId=c.UserId,Name=c.Name,Type=c.Type,Color=c.Color,Icon=c.Icon}; await r.AddAsync(x); return x.ToDto();} }
public class UpdateCategoryHandler(ICategoryRepository r):IRequestHandler<UpdateCategoryCommand,CategoryDto>{public async Task<CategoryDto> Handle(UpdateCategoryCommand c,CancellationToken ct){var x=await r.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Categoria não encontrada"); x.Name=c.Name;x.Type=c.Type;x.Color=c.Color;x.Icon=c.Icon; await r.UpdateAsync(x); return x.ToDto();}}
public class DeleteCategoryHandler(ICategoryRepository r,ITransactionRepository tr):IRequestHandler<DeleteCategoryCommand>{public async Task Handle(DeleteCategoryCommand c,CancellationToken ct){if(await tr.ExistsByCategoryIdAsync(c.Id,c.UserId)) throw new ConflictException("Categoria possui transações vinculadas"); await r.DeleteAsync(c.Id,c.UserId);}}

public class GetTransactionsHandler(ITransactionRepository r):IRequestHandler<GetTransactionsQuery,List<TransactionDto>>{public async Task<List<TransactionDto>> Handle(GetTransactionsQuery q,CancellationToken ct)=>(await r.GetByFilterAsync(q.UserId,q.Month,q.Year,q.Type,q.Status,q.CategoryId,q.AccountId)).Select(x=>x.ToDto()).ToList();}
public class GetTransactionByIdHandler(ITransactionRepository r):IRequestHandler<GetTransactionByIdQuery,TransactionDto>{public async Task<TransactionDto> Handle(GetTransactionByIdQuery q,CancellationToken ct)=>(await r.GetByIdAsync(q.Id,q.UserId)??throw new NotFoundException("Transação não encontrada")).ToDto();}
public class CreateTransactionHandler(ITransactionRepository txRepo, IAccountRepository accRepo, ICategoryRepository catRepo, ICacheService cache): IRequestHandler<CreateTransactionCommand, TransactionDto>{ public async Task<TransactionDto> Handle(CreateTransactionCommand c, CancellationToken ct){ if(c.Amount<=0) throw new ValidationException("Amount deve ser positivo"); var acc=await accRepo.GetByIdAsync(c.AccountId,c.UserId)??throw new ValidationException("Conta inválida"); _=await catRepo.GetByIdAsync(c.CategoryId,c.UserId)??throw new ValidationException("Categoria inválida"); var tx=new Transaction{UserId=c.UserId,AccountId=c.AccountId,CategoryId=c.CategoryId,Description=c.Description,Amount=c.Amount,Type=c.Type,Status=c.Status,Date=c.Date,DueDate=c.DueDate,Notes=c.Notes}; if(c.Status==TransactionStatus.Paid){acc.CurrentBalance += FinanceMapper.Impact(c.Type,c.Amount); await accRepo.UpdateAsync(acc);} await txRepo.AddAsync(tx); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto();} }
public class UpdateTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICategoryRepository catRepo,ICacheService cache): IRequestHandler<UpdateTransactionCommand, TransactionDto>{ public async Task<TransactionDto> Handle(UpdateTransactionCommand c,CancellationToken ct){ if(c.Amount<=0) throw new ValidationException("Amount deve ser positivo"); var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transação não encontrada"); var oldAcc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta antiga inválida"); var newAcc=await accRepo.GetByIdAsync(c.AccountId,c.UserId)??throw new ValidationException("Conta inválida"); _=await catRepo.GetByIdAsync(c.CategoryId,c.UserId)??throw new ValidationException("Categoria inválida"); if(tx.Status==TransactionStatus.Paid){ oldAcc.CurrentBalance -= FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(oldAcc);} tx.AccountId=c.AccountId;tx.CategoryId=c.CategoryId;tx.Description=c.Description;tx.Amount=c.Amount;tx.Type=c.Type;tx.Status=c.Status;tx.Date=c.Date;tx.DueDate=c.DueDate;tx.Notes=c.Notes; if(tx.Status==TransactionStatus.Paid){ newAcc.CurrentBalance += FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(newAcc);} await txRepo.UpdateAsync(tx); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto(); }}
public class DeleteTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICacheService cache):IRequestHandler<DeleteTransactionCommand>{ public async Task Handle(DeleteTransactionCommand c,CancellationToken ct){ var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transação não encontrada"); if(tx.Status==TransactionStatus.Paid){var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta inválida"); acc.CurrentBalance -= FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);} await txRepo.DeleteAsync(c.Id,c.UserId); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct);} }
public class MarkTransactionAsPaidHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICacheService cache):IRequestHandler<MarkTransactionAsPaidCommand,TransactionDto>{ public async Task<TransactionDto> Handle(MarkTransactionAsPaidCommand c,CancellationToken ct){var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transação não encontrada"); if(tx.Status!=TransactionStatus.Paid){var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta inválida"); acc.CurrentBalance += FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc); tx.Status=TransactionStatus.Paid; await txRepo.UpdateAsync(tx);} await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto();}}
public class MarkTransactionAsPendingHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICacheService cache):IRequestHandler<MarkTransactionAsPendingCommand,TransactionDto>{ public async Task<TransactionDto> Handle(MarkTransactionAsPendingCommand c,CancellationToken ct){var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transação não encontrada"); if(tx.Status==TransactionStatus.Paid){var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta inválida"); acc.CurrentBalance -= FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);} tx.Status=TransactionStatus.Pending; await txRepo.UpdateAsync(tx); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto();}}

public class GetMonthlySummaryHandler(IAccountRepository accountRepo,ITransactionRepository txRepo, ICacheService cache): IRequestHandler<GetMonthlySummaryQuery,MonthlySummaryDto>{ public async Task<MonthlySummaryDto> Handle(GetMonthlySummaryQuery q, CancellationToken ct){ var key=$"aurora:dashboard:{q.UserId}:{q.Month}:{q.Year}"; var c=await cache.GetAsync<MonthlySummaryDto>(key,ct); if(c is not null) return c; var total=await accountRepo.GetTotalBalanceAsync(q.UserId); var i=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Income,TransactionStatus.Paid); var e=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Expense,TransactionStatus.Paid); var pi=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Income,TransactionStatus.Pending); var pe=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Expense,TransactionStatus.Pending); var pc=await txRepo.CountAsync(q.UserId,q.Month,q.Year,TransactionStatus.Paid); var pdc=await txRepo.CountAsync(q.UserId,q.Month,q.Year,TransactionStatus.Pending); var recent=(await txRepo.RecentAsync(q.UserId)).Select(x=>x.ToDto()).ToList(); var d=new MonthlySummaryDto(total,i,e,i-e,pi,pe,pc,pdc,recent); await cache.SetAsync(key,d,TimeSpan.FromMinutes(5),ct); return d; }}
public class GetCategoryExpensesHandler(ITransactionRepository txRepo, ICategoryRepository catRepo): IRequestHandler<GetCategoryExpensesQuery,List<CategoryExpenseDto>>{ public async Task<List<CategoryExpenseDto>> Handle(GetCategoryExpensesQuery q,CancellationToken ct){var grouped=await txRepo.CategoryExpenseAsync(q.UserId,q.Month,q.Year); var cats=(await catRepo.GetByUserAsync(q.UserId)).ToDictionary(x=>x.Id,x=>x); var total=grouped.Sum(x=>x.Total); return grouped.Select(x=>{cats.TryGetValue(x.CategoryId,out var c); var p=total==0?0:Math.Round((x.Total/total)*100,2); return new CategoryExpenseDto(x.CategoryId,c?.Name??"N/A",c?.Color??"#94a3b8",x.Total,p);}).OrderByDescending(x=>x.Total).ToList(); }}
public class GetCashFlowHandler(ITransactionRepository txRepo): IRequestHandler<GetCashFlowQuery,List<CashFlowItemDto>>{ public async Task<List<CashFlowItemDto>> Handle(GetCashFlowQuery q,CancellationToken ct)=>(await txRepo.CashFlowAsync(q.UserId,q.Year)).Select(x=>new CashFlowItemDto(x.Month,x.Income,x.Expense,x.Income-x.Expense)).ToList(); }
