using Aurora.Application.Interfaces;
using Aurora.Domain.Entities;
using Aurora.Domain.Enums;
using Aurora.Domain.Exceptions;
using MediatR;

namespace Aurora.Application.Features;

public record AccountDto(string Id,string Name,AccountType Type,decimal InitialBalance,decimal CurrentBalance,string Color,bool IsArchived,decimal CreditLimit,int ClosingDay,int DueDay,decimal AvailableLimit,decimal CurrentInvoiceAmount);
public record CategoryDto(string Id,string Name,CategoryType Type,string Color,string Icon,bool IsDefault);
public record TransactionDto(string Id,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes,string? CreditCardInvoiceId,bool IsRecurring,RecurrenceType? RecurrenceType,int RecurrenceInterval,DateTime? RecurrenceEndDate,Guid? RecurrenceGroupId,int? RecurrenceIndex,int? TotalInstallments);
public record UpcomingDueDto(string Id,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes,string? CreditCardInvoiceId,bool IsRecurring,RecurrenceType? RecurrenceType,int RecurrenceInterval,DateTime? RecurrenceEndDate,Guid? RecurrenceGroupId,int? RecurrenceIndex,int? TotalInstallments,int DaysUntilDue);
public record CreditCardInvoiceDto(string Id,string AccountId,int Month,int Year,decimal TotalAmount,CreditCardInvoiceStatus Status,DateTime DueDate,DateTime? PaidAt,List<TransactionDto> Transactions);
public record MonthlySummaryDto(decimal TotalBalance, decimal MonthlyIncome, decimal MonthlyExpense, decimal MonthlyResult, decimal PendingIncome, decimal PendingExpense, int PaidTransactionsCount, int PendingTransactionsCount, List<TransactionDto> RecentTransactions, decimal PreviousMonthIncome, decimal PreviousMonthExpense, decimal IncomeVariation, decimal ExpenseVariation, decimal SavingsRate, List<UpcomingDueDto> UpcomingDueTransactions);
public record CategoryExpenseDto(string CategoryId,string CategoryName,string CategoryColor,decimal Total,decimal Percentage);
public record CashFlowItemDto(int Month,decimal Income,decimal Expense,decimal Result);
public record BudgetDto(string? Id,string CategoryId,string CategoryName,string CategoryIcon,string CategoryColor,int Month,int Year,decimal? LimitAmount,decimal SpentAmount,decimal UsagePercentage,bool HasBudget);
public record TransferDto(string Id,string FromAccountId,string ToAccountId,decimal Amount,DateTime Date,string Description,TransferStatus Status);
public record PagedResultDto<T>(List<T> Items,int TotalCount,int Page,int PageSize,int TotalPages);

public record GetAccountsQuery(string UserId): IRequest<List<AccountDto>>;
public record GetAccountByIdQuery(string UserId,string Id): IRequest<AccountDto>;
public record CreateAccountCommand(string UserId,string Name,AccountType Type,decimal InitialBalance,string Color,decimal CreditLimit=0,int ClosingDay=10,int DueDay=15): IRequest<AccountDto>;
public record UpdateAccountCommand(string UserId,string Id,string Name,AccountType Type,decimal InitialBalance,string Color,bool IsArchived,decimal CreditLimit=0,int ClosingDay=10,int DueDay=15): IRequest<AccountDto>;
public record ArchiveAccountCommand(string UserId,string Id): IRequest;
public record DeleteAccountCommand(string UserId,string Id): IRequest;

public record GetCategoriesQuery(string UserId): IRequest<List<CategoryDto>>;
public record CreateCategoryCommand(string UserId,string Name,CategoryType Type,string Color,string Icon): IRequest<CategoryDto>;
public record UpdateCategoryCommand(string UserId,string Id,string Name,CategoryType Type,string Color,string Icon): IRequest<CategoryDto>;
public record DeleteCategoryCommand(string UserId,string Id): IRequest;

public record GetTransactionsQuery(string UserId,int? Month,int? Year,TransactionType? Type,TransactionStatus? Status,string? CategoryId,string? AccountId,string? Search=null,DateTime? DateFrom=null,DateTime? DateTo=null,List<string>? AccountIds=null,List<string>? CategoryIds=null,decimal? MinAmount=null,decimal? MaxAmount=null,int Page=1,int PageSize=20): IRequest<PagedResultDto<TransactionDto>>;
public record ExportTransactionsCsvQuery(string UserId,int? Month,int? Year,TransactionType? Type,TransactionStatus? Status,string? CategoryId,string? AccountId,DateTime? DateFrom,DateTime? DateTo): IRequest<TransactionsCsvFile>;
public record TransactionsCsvFile(string FileName,string Content);
public record GetTransactionByIdQuery(string UserId,string Id): IRequest<TransactionDto>;
public record CreateTransactionCommand(string UserId,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes,bool IsRecurring=false,RecurrenceType? RecurrenceType=null,int RecurrenceInterval=1,DateTime? RecurrenceEndDate=null,int? TotalInstallments=null): IRequest<TransactionDto>;
public record UpdateTransactionCommand(string UserId,string Id,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes,bool IsRecurring=false,RecurrenceType? RecurrenceType=null,int RecurrenceInterval=1,DateTime? RecurrenceEndDate=null,int? TotalInstallments=null): IRequest<TransactionDto>;
public record DeleteTransactionCommand(string UserId,string Id): IRequest;
public record MarkTransactionAsPaidCommand(string UserId,string Id): IRequest<TransactionDto>;
public record MarkTransactionAsPendingCommand(string UserId,string Id): IRequest<TransactionDto>;
public record UpdateRecurringTransactionCommand(string UserId,string Id,string Scope,string AccountId,string CategoryId,string Description,decimal Amount,TransactionType Type,TransactionStatus Status,DateTime Date,DateTime? DueDate,string? Notes,bool IsRecurring=false,RecurrenceType? RecurrenceType=null,int RecurrenceInterval=1,DateTime? RecurrenceEndDate=null,int? TotalInstallments=null): IRequest<List<TransactionDto>>;
public record DeleteRecurringTransactionCommand(string UserId,string Id,string Scope): IRequest;

public record GetCreditCardInvoicesQuery(string UserId,string AccountId): IRequest<List<CreditCardInvoiceDto>>;
public record GetCreditCardInvoiceQuery(string UserId,string AccountId,int Month,int Year): IRequest<CreditCardInvoiceDto>;
public record PayCreditCardInvoiceCommand(string UserId,string Id,string SourceAccountId,decimal Amount): IRequest<CreditCardInvoiceDto>;

public record GetBudgetsQuery(string UserId,int Month,int Year): IRequest<List<BudgetDto>>;
public record UpsertBudgetCommand(string UserId,string CategoryId,int Month,int Year,decimal LimitAmount): IRequest<BudgetDto>;
public record DeleteBudgetCommand(string UserId,string Id): IRequest;

public record GetTransfersQuery(string UserId,int? Month,int? Year): IRequest<List<TransferDto>>;
public record CreateTransferCommand(string UserId,string FromAccountId,string ToAccountId,decimal Amount,DateTime Date,string Description): IRequest<TransferDto>;
public record DeleteTransferCommand(string UserId,string Id): IRequest;

public record GetMonthlySummaryQuery(string UserId,int Month,int Year): IRequest<MonthlySummaryDto>;
public record UpcomingDuesQuery(string UserId,int Days=7,string Status="pending"): IRequest<List<UpcomingDueDto>>;
public record GetCategoryExpensesQuery(string UserId,int Month,int Year): IRequest<List<CategoryExpenseDto>>;
public record GetCashFlowQuery(string UserId,int Year): IRequest<List<CashFlowItemDto>>;

public static class FinanceMapper {
 public static AccountDto ToDto(this Account x){var available=x.Type==AccountType.CreditCard?Math.Max(0,x.CreditLimit-x.CurrentBalance):x.CurrentBalance; return new(x.Id,x.Name,x.Type,x.InitialBalance,x.CurrentBalance,x.Color,x.IsArchived,x.CreditLimit,x.ClosingDay,x.DueDay,available,x.Type==AccountType.CreditCard?x.CurrentBalance:0);}
 public static CategoryDto ToDto(this Category x)=>new(x.Id,x.Name,x.Type,x.Color,x.Icon,x.IsDefault);
 public static TransactionDto ToDto(this Transaction x)=>new(x.Id,x.AccountId,x.CategoryId,x.Description,x.Amount,x.Type,x.Status,x.Date,x.DueDate,x.Notes,x.CreditCardInvoiceId,x.IsRecurring,x.RecurrenceType,x.RecurrenceInterval,x.RecurrenceEndDate,x.RecurrenceGroupId,x.RecurrenceIndex,x.TotalInstallments);
 public static UpcomingDueDto ToUpcomingDueDto(this Transaction x){var today=DateTime.UtcNow.Date; var due=x.DueDate?.Date??x.Date.Date; var days=(int)(due-today).TotalDays; return new(x.Id,x.AccountId,x.CategoryId,x.Description,x.Amount,x.Type,x.Status,x.Date,x.DueDate,x.Notes,x.CreditCardInvoiceId,x.IsRecurring,x.RecurrenceType,x.RecurrenceInterval,x.RecurrenceEndDate,x.RecurrenceGroupId,x.RecurrenceIndex,x.TotalInstallments,days);}
 public static TransferDto ToDto(this Transfer x)=>new(x.Id,x.FromAccountId,x.ToAccountId,x.Amount,x.Date,x.Description,x.Status);
 public static CreditCardInvoiceDto ToDto(this CreditCardInvoice x,List<Transaction> transactions)=>new(x.Id,x.AccountId,x.Month,x.Year,x.TotalAmount,x.Status,x.DueDate,x.PaidAt,transactions.Select(t=>t.ToDto()).ToList());
 public static decimal Impact(TransactionType t, decimal amount)=> t==TransactionType.Income ? amount : -amount;
}

public static class CreditCardInvoiceCalculator {
 public static (int Month,int Year) Period(DateTime date,int closingDay){var period=new DateTime(date.Year,date.Month,1); if(date.Day>closingDay) period=period.AddMonths(1); return (period.Month,period.Year);}
 public static DateTime DueDate(int month,int year,int dueDay)=>new(year,month,Math.Clamp(dueDay,1,28));
}

public static class RecurrenceGenerator {
 public static List<Transaction> Generate(CreateTransactionCommand c){var groupId=Guid.NewGuid(); var type=c.TotalInstallments.HasValue?Domain.Enums.RecurrenceType.Monthly:c.RecurrenceType??Domain.Enums.RecurrenceType.Monthly; var interval=Math.Max(1,c.RecurrenceInterval); var total=c.TotalInstallments??CalculateOpenEndedCount(c.Date,c.RecurrenceEndDate,type,interval); var list=new List<Transaction>(); for(var i=0;i<total;i++){var date=AddInterval(c.Date,type,interval,i); if(c.RecurrenceEndDate.HasValue&&date.Date>c.RecurrenceEndDate.Value.Date) break; list.Add(new Transaction{UserId=c.UserId,AccountId=c.AccountId,CategoryId=c.CategoryId,Description=c.TotalInstallments.HasValue?$"{c.Description} ({i+1}/{total})":c.Description,Amount=c.Amount,Type=c.Type,Status=i==0?c.Status:TransactionStatus.Pending,Date=date,DueDate=c.DueDate.HasValue?AddInterval(c.DueDate.Value,type,interval,i):null,Notes=c.Notes,IsRecurring=true,RecurrenceType=type,RecurrenceInterval=interval,RecurrenceEndDate=c.RecurrenceEndDate,RecurrenceGroupId=groupId,RecurrenceIndex=i+1,TotalInstallments=c.TotalInstallments});} return list;}
 public static DateTime AddInterval(DateTime date,RecurrenceType type,int interval,int index)=>type switch{RecurrenceType.Weekly=>date.AddDays(7*interval*index),RecurrenceType.Yearly=>date.AddYears(interval*index),_=>date.AddMonths(interval*index)};
 static int CalculateOpenEndedCount(DateTime start,DateTime? end,RecurrenceType type,int interval){var limit=end?.Date??start.AddMonths(12).Date; var count=0; var current=start; while(current.Date<=limit&&count<60){count++; current=AddInterval(start,type,interval,count);} return Math.Max(count,1);}
}

public static class TransactionPostingService {
 public static async Task<Transaction> PostAsync(Transaction tx,ITransactionRepository txRepo,IAccountRepository accRepo,ICategoryRepository catRepo,ICreditCardInvoiceRepository invoiceRepo,string userId){var acc=await accRepo.GetByIdAsync(tx.AccountId,userId)??throw new ValidationException("Conta invalida"); if(!string.IsNullOrWhiteSpace(tx.CategoryId)) _=await catRepo.GetByIdAsync(tx.CategoryId,userId)??throw new ValidationException("Categoria invalida"); if(acc.Type==AccountType.CreditCard&&tx.Type==TransactionType.Expense){var period=CreditCardInvoiceCalculator.Period(tx.Date,acc.ClosingDay); var invoice=await invoiceRepo.GetByPeriodAsync(acc.Id,userId,period.Month,period.Year); if(invoice is null){invoice=new CreditCardInvoice{UserId=userId,AccountId=acc.Id,Month=period.Month,Year=period.Year,DueDate=CreditCardInvoiceCalculator.DueDate(period.Month,period.Year,acc.DueDay)}; await invoiceRepo.AddAsync(invoice);} invoice.TotalAmount+=tx.Amount; await invoiceRepo.UpdateAsync(invoice); tx.Status=TransactionStatus.Pending; tx.CreditCardInvoiceId=invoice.Id; acc.CurrentBalance=await invoiceRepo.SumOpenByAccountAsync(acc.Id,userId); await accRepo.UpdateAsync(acc);} else if(tx.Status==TransactionStatus.Paid){acc.CurrentBalance+=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);} await txRepo.AddAsync(tx); return tx;}
}

public class GetAccountsHandler(IAccountRepository r):IRequestHandler<GetAccountsQuery,List<AccountDto>>{public async Task<List<AccountDto>> Handle(GetAccountsQuery q,CancellationToken ct)=>(await r.GetByUserAsync(q.UserId)).Select(x=>x.ToDto()).ToList();}
public class GetAccountByIdHandler(IAccountRepository r):IRequestHandler<GetAccountByIdQuery,AccountDto>{public async Task<AccountDto> Handle(GetAccountByIdQuery q,CancellationToken ct)=>(await r.GetByIdAsync(q.Id,q.UserId)??throw new NotFoundException("Conta nao encontrada")).ToDto();}
public class CreateAccountHandler(IAccountRepository r):IRequestHandler<CreateAccountCommand,AccountDto>{public async Task<AccountDto> Handle(CreateAccountCommand c,CancellationToken ct){ValidateCreditCard(c.Type,c.CreditLimit,c.ClosingDay,c.DueDay); var current=c.Type==AccountType.CreditCard?0:c.InitialBalance; var a=new Account{UserId=c.UserId,Name=c.Name,Type=c.Type,InitialBalance=c.InitialBalance,CurrentBalance=current,Color=c.Color,CreditLimit=c.Type==AccountType.CreditCard?c.CreditLimit:0,ClosingDay=c.ClosingDay,DueDay=c.DueDay}; await r.AddAsync(a); return a.ToDto();} static void ValidateCreditCard(AccountType type,decimal limit,int closingDay,int dueDay){if(type!=AccountType.CreditCard) return; if(limit<=0) throw new ValidationException("Limite do cartao deve ser positivo"); if(closingDay<1||closingDay>28||dueDay<1||dueDay>28) throw new ValidationException("Fechamento e vencimento devem estar entre 1 e 28");}}
public class UpdateAccountHandler(IAccountRepository r):IRequestHandler<UpdateAccountCommand,AccountDto>{public async Task<AccountDto> Handle(UpdateAccountCommand c,CancellationToken ct){var a=await r.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Conta nao encontrada"); if(c.Type==AccountType.CreditCard){if(c.CreditLimit<=0) throw new ValidationException("Limite do cartao deve ser positivo"); if(c.ClosingDay<1||c.ClosingDay>28||c.DueDay<1||c.DueDay>28) throw new ValidationException("Fechamento e vencimento devem estar entre 1 e 28");} a.Name=c.Name;a.Type=c.Type;a.Color=c.Color;a.IsArchived=c.IsArchived;a.CreditLimit=c.Type==AccountType.CreditCard?c.CreditLimit:0;a.ClosingDay=c.ClosingDay;a.DueDay=c.DueDay; await r.UpdateAsync(a); return a.ToDto();}}
public class ArchiveAccountHandler(IAccountRepository r):IRequestHandler<ArchiveAccountCommand>{public async Task Handle(ArchiveAccountCommand c,CancellationToken ct){var a=await r.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Conta nao encontrada"); a.IsArchived=true; await r.UpdateAsync(a);}}
public class DeleteAccountHandler(IAccountRepository r,ITransactionRepository tr):IRequestHandler<DeleteAccountCommand>{public async Task Handle(DeleteAccountCommand c,CancellationToken ct){if(await tr.ExistsByAccountIdAsync(c.Id,c.UserId)) throw new ConflictException("Conta possui transacoes vinculadas"); await r.DeleteAsync(c.Id,c.UserId);}}

public class GetCategoriesHandler(ICategoryRepository r):IRequestHandler<GetCategoriesQuery,List<CategoryDto>>{public async Task<List<CategoryDto>> Handle(GetCategoriesQuery q,CancellationToken ct)=>(await r.GetByUserAsync(q.UserId)).Select(x=>x.ToDto()).ToList();}
public class CreateCategoryHandler(ICategoryRepository r):IRequestHandler<CreateCategoryCommand,CategoryDto>{public async Task<CategoryDto> Handle(CreateCategoryCommand c,CancellationToken ct){var x=new Category{UserId=c.UserId,Name=c.Name,Type=c.Type,Color=c.Color,Icon=c.Icon}; await r.AddAsync(x); return x.ToDto();} }
public class UpdateCategoryHandler(ICategoryRepository r):IRequestHandler<UpdateCategoryCommand,CategoryDto>{public async Task<CategoryDto> Handle(UpdateCategoryCommand c,CancellationToken ct){var x=await r.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Categoria nao encontrada"); x.Name=c.Name;x.Type=c.Type;x.Color=c.Color;x.Icon=c.Icon; await r.UpdateAsync(x); return x.ToDto();}}
public class DeleteCategoryHandler(ICategoryRepository r,ITransactionRepository tr):IRequestHandler<DeleteCategoryCommand>{public async Task Handle(DeleteCategoryCommand c,CancellationToken ct){if(await tr.ExistsByCategoryIdAsync(c.Id,c.UserId)) throw new ConflictException("Categoria possui transacoes vinculadas"); await r.DeleteAsync(c.Id,c.UserId);}}

public class GetTransactionsHandler(ITransactionRepository r):IRequestHandler<GetTransactionsQuery,PagedResultDto<TransactionDto>>{public async Task<PagedResultDto<TransactionDto>> Handle(GetTransactionsQuery q,CancellationToken ct){var page=q.Page<1?1:q.Page; var pageSize=q.PageSize<1?20:(q.PageSize>200?200:q.PageSize); var filter=new TransactionFilter(q.UserId,q.Month,q.Year,q.Type,q.Status,q.CategoryId,q.AccountId,q.Search,q.DateFrom,q.DateTo,q.AccountIds,q.CategoryIds,q.MinAmount,q.MaxAmount); var (items,total)=await r.GetPagedAsync(filter,page,pageSize); var totalPages=pageSize<=0?0:(int)Math.Ceiling(total/(double)pageSize); return new PagedResultDto<TransactionDto>(items.Select(x=>x.ToDto()).ToList(),total,page,pageSize,totalPages);}}
public class ExportTransactionsCsvHandler(ITransactionRepository txRepo, IAccountRepository accRepo, ICategoryRepository catRepo): IRequestHandler<ExportTransactionsCsvQuery,TransactionsCsvFile>{
 public async Task<TransactionsCsvFile> Handle(ExportTransactionsCsvQuery q, CancellationToken ct){
  var filter=new TransactionFilter(q.UserId,q.Month,q.Year,q.Type,q.Status,q.CategoryId,q.AccountId,null,q.DateFrom,q.DateTo,null,null,null,null);
  var (items,_)=await txRepo.GetPagedAsync(filter, 1, int.MaxValue);
  var accounts=(await accRepo.GetByUserAsync(q.UserId)).ToDictionary(x=>x.Id,x=>x.Name);
  var categories=(await catRepo.GetByUserAsync(q.UserId)).ToDictionary(x=>x.Id,x=>x.Name);
  var sb=new System.Text.StringBuilder();
  sb.AppendLine("Data;Descricao;Tipo;Categoria;Conta;Valor;Status;Vencimento;Notas");
  foreach(var tx in items.OrderByDescending(x=>x.Date)){
   var row=string.Join(";", new[]{
    tx.Date.ToString("yyyy-MM-dd"),
    CsvEscape(tx.Description),
    tx.Type.ToString(),
    CsvEscape(categories.GetValueOrDefault(tx.CategoryId, "")),
    CsvEscape(accounts.GetValueOrDefault(tx.AccountId, "")),
    tx.Amount.ToString(System.Globalization.CultureInfo.InvariantCulture),
    tx.Status.ToString(),
    tx.DueDate?.ToString("yyyy-MM-dd") ?? "",
    CsvEscape(tx.Notes ?? "")
   });
   sb.AppendLine(row);
  }
  var monthLabel=(q.DateFrom?.Month ?? q.Month ?? DateTime.UtcNow.Month).ToString("00");
  var yearLabel=(q.DateFrom?.Year ?? q.Year ?? DateTime.UtcNow.Year).ToString();
  return new TransactionsCsvFile($"aurora-transacoes-{monthLabel}-{yearLabel}.csv", sb.ToString());
 }
 static string CsvEscape(string value){if(string.IsNullOrEmpty(value)) return ""; var needsQuotes=value.Contains(';')||value.Contains('"')||value.Contains('\n')||value.Contains('\r'); var escaped=value.Replace("\"","\"\""); return needsQuotes?$"\"{escaped}\"":escaped;}
}
public class GetTransactionByIdHandler(ITransactionRepository r):IRequestHandler<GetTransactionByIdQuery,TransactionDto>{public async Task<TransactionDto> Handle(GetTransactionByIdQuery q,CancellationToken ct)=>(await r.GetByIdAsync(q.Id,q.UserId)??throw new NotFoundException("Transacao nao encontrada")).ToDto();}
public class CreateTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICategoryRepository catRepo,ICreditCardInvoiceRepository invoiceRepo,ICacheService cache): IRequestHandler<CreateTransactionCommand,TransactionDto>{public async Task<TransactionDto> Handle(CreateTransactionCommand c,CancellationToken ct){if(c.Amount<=0) throw new ValidationException("Amount deve ser positivo"); var transactions=c.IsRecurring||c.TotalInstallments.HasValue?RecurrenceGenerator.Generate(c):[new Transaction{UserId=c.UserId,AccountId=c.AccountId,CategoryId=c.CategoryId,Description=c.Description,Amount=c.Amount,Type=c.Type,Status=c.Status,Date=c.Date,DueDate=c.DueDate,Notes=c.Notes}]; TransactionDto? first=null; foreach(var tx in transactions){var saved=await TransactionPostingService.PostAsync(tx,txRepo,accRepo,catRepo,invoiceRepo,c.UserId); first??=saved.ToDto();} await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return first!;}}
public class UpdateTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICategoryRepository catRepo,ICacheService cache): IRequestHandler<UpdateTransactionCommand,TransactionDto>{public async Task<TransactionDto> Handle(UpdateTransactionCommand c,CancellationToken ct){if(c.Amount<=0) throw new ValidationException("Amount deve ser positivo"); var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transacao nao encontrada"); var oldAcc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta antiga invalida"); var newAcc=await accRepo.GetByIdAsync(c.AccountId,c.UserId)??throw new ValidationException("Conta invalida"); _=await catRepo.GetByIdAsync(c.CategoryId,c.UserId)??throw new ValidationException("Categoria invalida"); if(tx.Status==TransactionStatus.Paid&&oldAcc.Type!=AccountType.CreditCard){oldAcc.CurrentBalance-=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(oldAcc);} tx.AccountId=c.AccountId;tx.CategoryId=c.CategoryId;tx.Description=c.Description;tx.Amount=c.Amount;tx.Type=c.Type;tx.Status=c.Status;tx.Date=c.Date;tx.DueDate=c.DueDate;tx.Notes=c.Notes; if(tx.Status==TransactionStatus.Paid&&newAcc.Type!=AccountType.CreditCard){newAcc.CurrentBalance+=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(newAcc);} await txRepo.UpdateAsync(tx); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto();}}
public class DeleteTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICreditCardInvoiceRepository invoiceRepo,ICacheService cache):IRequestHandler<DeleteTransactionCommand>{public async Task Handle(DeleteTransactionCommand c,CancellationToken ct){var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transacao nao encontrada"); var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta invalida"); if(acc.Type==AccountType.CreditCard&&!string.IsNullOrWhiteSpace(tx.CreditCardInvoiceId)){var invoice=await invoiceRepo.GetByIdAsync(tx.CreditCardInvoiceId,c.UserId); if(invoice is not null&&invoice.Status!=CreditCardInvoiceStatus.Paid){invoice.TotalAmount=Math.Max(0,invoice.TotalAmount-tx.Amount); await invoiceRepo.UpdateAsync(invoice); acc.CurrentBalance=await invoiceRepo.SumOpenByAccountAsync(acc.Id,c.UserId); await accRepo.UpdateAsync(acc);}} else if(tx.Status==TransactionStatus.Paid){acc.CurrentBalance-=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);} await txRepo.DeleteAsync(tx.Id,c.UserId); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct);}}
public class MarkTransactionAsPaidHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICacheService cache):IRequestHandler<MarkTransactionAsPaidCommand,TransactionDto>{public async Task<TransactionDto> Handle(MarkTransactionAsPaidCommand c,CancellationToken ct){var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transacao nao encontrada"); if(tx.Status!=TransactionStatus.Paid){var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta invalida"); if(acc.Type!=AccountType.CreditCard){acc.CurrentBalance+=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);} tx.Status=TransactionStatus.Paid; await txRepo.UpdateAsync(tx);} await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto();}}
public class MarkTransactionAsPendingHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICacheService cache):IRequestHandler<MarkTransactionAsPendingCommand,TransactionDto>{public async Task<TransactionDto> Handle(MarkTransactionAsPendingCommand c,CancellationToken ct){var tx=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transacao nao encontrada"); if(tx.Status==TransactionStatus.Paid){var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta invalida"); if(acc.Type!=AccountType.CreditCard){acc.CurrentBalance-=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);}} tx.Status=TransactionStatus.Pending; await txRepo.UpdateAsync(tx); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return tx.ToDto();}}
public class UpdateRecurringTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICategoryRepository catRepo,ICacheService cache):IRequestHandler<UpdateRecurringTransactionCommand,List<TransactionDto>>{public async Task<List<TransactionDto>> Handle(UpdateRecurringTransactionCommand c,CancellationToken ct){var selected=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transacao nao encontrada"); var targets=await RecurrenceScope.SelectAsync(txRepo,selected,c.UserId,c.Scope); foreach(var tx in targets){tx.AccountId=c.AccountId;tx.CategoryId=c.CategoryId;tx.Description=tx.TotalInstallments.HasValue&&tx.RecurrenceIndex.HasValue?$"{StripInstallmentSuffix(c.Description)} ({tx.RecurrenceIndex}/{tx.TotalInstallments})":c.Description;tx.Amount=c.Amount;tx.Type=c.Type;tx.Status=c.Status;tx.DueDate=c.DueDate.HasValue?RecurrenceGenerator.AddInterval(c.DueDate.Value,c.RecurrenceType??tx.RecurrenceType??Domain.Enums.RecurrenceType.Monthly,c.RecurrenceInterval>0?c.RecurrenceInterval:tx.RecurrenceInterval,(tx.RecurrenceIndex??1)-1):null;tx.Notes=c.Notes;tx.IsRecurring=c.IsRecurring||tx.IsRecurring;tx.RecurrenceType=c.RecurrenceType??tx.RecurrenceType;tx.RecurrenceInterval=Math.Max(1,c.RecurrenceInterval);tx.RecurrenceEndDate=c.RecurrenceEndDate;tx.TotalInstallments=c.TotalInstallments??tx.TotalInstallments; if(!string.IsNullOrWhiteSpace(tx.CategoryId)) _=await catRepo.GetByIdAsync(tx.CategoryId,c.UserId)??throw new ValidationException("Categoria invalida"); _=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta invalida"); await txRepo.UpdateAsync(tx);} await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return targets.Select(x=>x.ToDto()).ToList();} static string StripInstallmentSuffix(string value){var idx=value.LastIndexOf(" (",StringComparison.Ordinal); return idx>0?value[..idx]:value;}}
public class DeleteRecurringTransactionHandler(ITransactionRepository txRepo,IAccountRepository accRepo,ICreditCardInvoiceRepository invoiceRepo,ICacheService cache):IRequestHandler<DeleteRecurringTransactionCommand>{public async Task Handle(DeleteRecurringTransactionCommand c,CancellationToken ct){var selected=await txRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transacao nao encontrada"); var targets=await RecurrenceScope.SelectAsync(txRepo,selected,c.UserId,c.Scope); foreach(var tx in targets){var acc=await accRepo.GetByIdAsync(tx.AccountId,c.UserId)??throw new ValidationException("Conta invalida"); if(acc.Type==AccountType.CreditCard&&!string.IsNullOrWhiteSpace(tx.CreditCardInvoiceId)){var invoice=await invoiceRepo.GetByIdAsync(tx.CreditCardInvoiceId,c.UserId); if(invoice is not null&&invoice.Status!=CreditCardInvoiceStatus.Paid){invoice.TotalAmount=Math.Max(0,invoice.TotalAmount-tx.Amount); await invoiceRepo.UpdateAsync(invoice); acc.CurrentBalance=await invoiceRepo.SumOpenByAccountAsync(acc.Id,c.UserId); await accRepo.UpdateAsync(acc);}} else if(tx.Status==TransactionStatus.Paid){acc.CurrentBalance-=FinanceMapper.Impact(tx.Type,tx.Amount); await accRepo.UpdateAsync(acc);} await txRepo.DeleteAsync(tx.Id,c.UserId);} await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct);}}
public static class RecurrenceScope { public static async Task<List<Transaction>> SelectAsync(ITransactionRepository repo,Transaction selected,string userId,string scope){if(!selected.RecurrenceGroupId.HasValue||scope=="this") return [selected]; var group=await repo.GetByRecurrenceGroupAsync(selected.RecurrenceGroupId.Value,userId); return scope switch{"future"=>group.Where(x=>x.Date>=selected.Date).ToList(),"all"=>group,_=>[selected]};}}

public class GetCreditCardInvoicesHandler(IAccountRepository accountRepo,ICreditCardInvoiceRepository invoiceRepo,ITransactionRepository txRepo):IRequestHandler<GetCreditCardInvoicesQuery,List<CreditCardInvoiceDto>>{public async Task<List<CreditCardInvoiceDto>> Handle(GetCreditCardInvoicesQuery q,CancellationToken ct){var account=await accountRepo.GetByIdAsync(q.AccountId,q.UserId)??throw new NotFoundException("Conta nao encontrada"); if(account.Type!=AccountType.CreditCard) throw new ValidationException("Conta nao e cartao de credito"); var invoices=await invoiceRepo.GetByAccountAsync(q.AccountId,q.UserId); var result=new List<CreditCardInvoiceDto>(); foreach(var invoice in invoices){result.Add(invoice.ToDto(await txRepo.GetByInvoiceIdAsync(invoice.Id,q.UserId)));} return result;}}
public class GetCreditCardInvoiceHandler(IAccountRepository accountRepo,ICreditCardInvoiceRepository invoiceRepo,ITransactionRepository txRepo):IRequestHandler<GetCreditCardInvoiceQuery,CreditCardInvoiceDto>{public async Task<CreditCardInvoiceDto> Handle(GetCreditCardInvoiceQuery q,CancellationToken ct){var account=await accountRepo.GetByIdAsync(q.AccountId,q.UserId)??throw new NotFoundException("Conta nao encontrada"); if(account.Type!=AccountType.CreditCard) throw new ValidationException("Conta nao e cartao de credito"); var invoice=await invoiceRepo.GetByPeriodAsync(q.AccountId,q.UserId,q.Month,q.Year); if(invoice is null){invoice=new CreditCardInvoice{UserId=q.UserId,AccountId=q.AccountId,Month=q.Month,Year=q.Year,DueDate=CreditCardInvoiceCalculator.DueDate(q.Month,q.Year,account.DueDay)}; await invoiceRepo.AddAsync(invoice);} return invoice.ToDto(await txRepo.GetByInvoiceIdAsync(invoice.Id,q.UserId));}}
public class PayCreditCardInvoiceHandler(IAccountRepository accountRepo,ICreditCardInvoiceRepository invoiceRepo,ITransactionRepository txRepo,ICacheService cache):IRequestHandler<PayCreditCardInvoiceCommand,CreditCardInvoiceDto>{public async Task<CreditCardInvoiceDto> Handle(PayCreditCardInvoiceCommand c,CancellationToken ct){if(c.Amount<=0) throw new ValidationException("Valor de pagamento deve ser positivo"); var invoice=await invoiceRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Fatura nao encontrada"); if(invoice.Status==CreditCardInvoiceStatus.Paid) throw new ValidationException("Fatura ja paga"); var card=await accountRepo.GetByIdAsync(invoice.AccountId,c.UserId)??throw new NotFoundException("Cartao nao encontrado"); var source=await accountRepo.GetByIdAsync(c.SourceAccountId,c.UserId)??throw new ValidationException("Conta de debito invalida"); if(source.Type==AccountType.CreditCard) throw new ValidationException("Pagamento de fatura deve sair de uma conta de debito"); source.CurrentBalance-=c.Amount; await accountRepo.UpdateAsync(source); invoice.Status=CreditCardInvoiceStatus.Paid; invoice.PaidAt=DateTime.UtcNow; await invoiceRepo.UpdateAsync(invoice); card.CurrentBalance=await invoiceRepo.SumOpenByAccountAsync(card.Id,c.UserId); await accountRepo.UpdateAsync(card); var tx=new Transaction{UserId=c.UserId,AccountId=source.Id,CategoryId="",Description=$"Pagamento fatura {card.Name} {invoice.Month:00}/{invoice.Year}",Amount=c.Amount,Type=TransactionType.Expense,Status=TransactionStatus.Paid,Date=DateTime.UtcNow,DueDate=invoice.DueDate,Notes="Pagamento de fatura de cartao de credito",CreditCardInvoiceId=invoice.Id}; await txRepo.AddAsync(tx); await cache.RemoveByPrefixAsync($"aurora:dashboard:{c.UserId}",ct); return invoice.ToDto(await txRepo.GetByInvoiceIdAsync(invoice.Id,c.UserId));}}

public static class BudgetMapper {
 public static BudgetDto ToBudgetDto(Category category,Budget? budget,decimal spent,int month,int year){var limit=budget?.LimitAmount; var usage=limit.HasValue&&limit.Value>0?Math.Round((spent/limit.Value)*100,2):0; return new BudgetDto(budget?.Id,category.Id,category.Name,category.Icon,category.Color,month,year,limit,spent,usage,budget is not null);}
}

public class GetBudgetsHandler(IBudgetRepository budgetRepo,ICategoryRepository categoryRepo,ITransactionRepository txRepo):IRequestHandler<GetBudgetsQuery,List<BudgetDto>>{public async Task<List<BudgetDto>> Handle(GetBudgetsQuery q,CancellationToken ct){var categories=(await categoryRepo.GetByUserAsync(q.UserId)).Where(x=>x.Type==CategoryType.Expense).OrderBy(x=>x.Name).ToList(); var budgets=(await budgetRepo.GetByMonthAsync(q.UserId,q.Month,q.Year)).ToDictionary(x=>x.CategoryId,x=>x); var spent=(await txRepo.CategoryExpenseAsync(q.UserId,q.Month,q.Year)).ToDictionary(x=>x.CategoryId,x=>x.Total); return categories.Select(category=>BudgetMapper.ToBudgetDto(category,budgets.GetValueOrDefault(category.Id),spent.GetValueOrDefault(category.Id),q.Month,q.Year)).OrderByDescending(x=>x.HasBudget&&x.LimitAmount>0?x.UsagePercentage:-1).ThenBy(x=>x.CategoryName).ToList();}}
public class UpsertBudgetHandler(IBudgetRepository budgetRepo,ICategoryRepository categoryRepo,ITransactionRepository txRepo):IRequestHandler<UpsertBudgetCommand,BudgetDto>{public async Task<BudgetDto> Handle(UpsertBudgetCommand c,CancellationToken ct){if(c.Month<1||c.Month>12) throw new ValidationException("Mes invalido"); if(c.Year<2000) throw new ValidationException("Ano invalido"); if(c.LimitAmount<=0) throw new ValidationException("Limite deve ser positivo"); var category=await categoryRepo.GetByIdAsync(c.CategoryId,c.UserId)??throw new ValidationException("Categoria invalida"); if(category.Type!=CategoryType.Expense) throw new ValidationException("Orcamento deve usar categoria de despesa"); var budget=await budgetRepo.GetByCategoryPeriodAsync(c.UserId,c.CategoryId,c.Month,c.Year); if(budget is null){budget=new Budget{UserId=c.UserId,CategoryId=c.CategoryId,Month=c.Month,Year=c.Year,LimitAmount=c.LimitAmount}; await budgetRepo.AddAsync(budget);} else {budget.LimitAmount=c.LimitAmount; await budgetRepo.UpdateAsync(budget);} var spent=(await txRepo.CategoryExpenseAsync(c.UserId,c.Month,c.Year)).FirstOrDefault(x=>x.CategoryId==c.CategoryId).Total; return BudgetMapper.ToBudgetDto(category,budget,spent,c.Month,c.Year);}}
public class DeleteBudgetHandler(IBudgetRepository budgetRepo):IRequestHandler<DeleteBudgetCommand>{public async Task Handle(DeleteBudgetCommand c,CancellationToken ct){var budget=await budgetRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Orcamento nao encontrado"); await budgetRepo.DeleteAsync(budget.Id,c.UserId);}}

public class GetTransfersHandler(ITransferRepository transferRepo):IRequestHandler<GetTransfersQuery,List<TransferDto>>{public async Task<List<TransferDto>> Handle(GetTransfersQuery q,CancellationToken ct)=>(await transferRepo.GetByFilterAsync(q.UserId,q.Month,q.Year)).Select(x=>x.ToDto()).ToList();}
public class CreateTransferHandler(ITransferRepository transferRepo,IAccountRepository accountRepo):IRequestHandler<CreateTransferCommand,TransferDto>{public async Task<TransferDto> Handle(CreateTransferCommand c,CancellationToken ct){if(c.Amount<=0) throw new ValidationException("Valor da transferencia deve ser positivo"); if(c.FromAccountId==c.ToAccountId) throw new ValidationException("Conta de origem e destino devem ser diferentes"); var from=await accountRepo.GetByIdAsync(c.FromAccountId,c.UserId)??throw new ValidationException("Conta de origem invalida"); var to=await accountRepo.GetByIdAsync(c.ToAccountId,c.UserId)??throw new ValidationException("Conta de destino invalida"); if(from.Type==AccountType.CreditCard||to.Type==AccountType.CreditCard) throw new ValidationException("Transferencia nao usa cartao de credito"); var originUpdated=false; var destinationUpdated=false; try{from.CurrentBalance-=c.Amount; await accountRepo.UpdateAsync(from); originUpdated=true; to.CurrentBalance+=c.Amount; await accountRepo.UpdateAsync(to); destinationUpdated=true; var transfer=new Transfer{UserId=c.UserId,FromAccountId=from.Id,ToAccountId=to.Id,Amount=c.Amount,Date=c.Date,Description=c.Description,Status=TransferStatus.Completed}; await transferRepo.AddAsync(transfer); return transfer.ToDto();}catch{if(destinationUpdated){to.CurrentBalance-=c.Amount; await accountRepo.UpdateAsync(to);} if(originUpdated){from.CurrentBalance+=c.Amount; await accountRepo.UpdateAsync(from);} throw;}}}
public class DeleteTransferHandler(ITransferRepository transferRepo,IAccountRepository accountRepo):IRequestHandler<DeleteTransferCommand>{public async Task Handle(DeleteTransferCommand c,CancellationToken ct){var transfer=await transferRepo.GetByIdAsync(c.Id,c.UserId)??throw new NotFoundException("Transferencia nao encontrada"); var from=await accountRepo.GetByIdAsync(transfer.FromAccountId,c.UserId)??throw new ValidationException("Conta de origem invalida"); var to=await accountRepo.GetByIdAsync(transfer.ToAccountId,c.UserId)??throw new ValidationException("Conta de destino invalida"); var originReverted=false; var destinationReverted=false; try{from.CurrentBalance+=transfer.Amount; await accountRepo.UpdateAsync(from); originReverted=true; to.CurrentBalance-=transfer.Amount; await accountRepo.UpdateAsync(to); destinationReverted=true; await transferRepo.DeleteAsync(transfer.Id,c.UserId);}catch{if(destinationReverted){to.CurrentBalance+=transfer.Amount; await accountRepo.UpdateAsync(to);} if(originReverted){from.CurrentBalance-=transfer.Amount; await accountRepo.UpdateAsync(from);} throw;}}}

public class GetMonthlySummaryHandler(IAccountRepository accountRepo,ITransactionRepository txRepo, ICacheService cache): IRequestHandler<GetMonthlySummaryQuery,MonthlySummaryDto>{ public async Task<MonthlySummaryDto> Handle(GetMonthlySummaryQuery q, CancellationToken ct){ var key=$"aurora:dashboard:{q.UserId}:{q.Month}:{q.Year}:v3"; var c=await cache.GetAsync<MonthlySummaryDto>(key,ct); if(c is not null) return c; var total=await accountRepo.GetTotalBalanceAsync(q.UserId); var i=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Income,TransactionStatus.Paid); var e=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Expense,TransactionStatus.Paid); var prev=new DateTime(q.Year,q.Month,1).AddMonths(-1); var prevIncome=await txRepo.SumAsync(q.UserId,prev.Month,prev.Year,TransactionType.Income,TransactionStatus.Paid); var prevExpense=await txRepo.SumAsync(q.UserId,prev.Month,prev.Year,TransactionType.Expense,TransactionStatus.Paid); var incomeVar=Variation(i,prevIncome); var expenseVar=Variation(e,prevExpense); var savings=i==0?0:Math.Round(((i-e)/i)*100,2); var pi=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Income,TransactionStatus.Pending); var pe=await txRepo.SumAsync(q.UserId,q.Month,q.Year,TransactionType.Expense,TransactionStatus.Pending); var pc=await txRepo.CountAsync(q.UserId,q.Month,q.Year,TransactionStatus.Paid); var pdc=await txRepo.CountAsync(q.UserId,q.Month,q.Year,TransactionStatus.Pending); var recent=(await txRepo.RecentAsync(q.UserId)).Select(x=>x.ToDto()).ToList(); var upcoming=(await txRepo.UpcomingDueAsync(q.UserId,7)).Select(x=>x.ToUpcomingDueDto()).ToList(); var d=new MonthlySummaryDto(total,i,e,i-e,pi,pe,pc,pdc,recent,prevIncome,prevExpense,incomeVar,expenseVar,savings,upcoming); await cache.SetAsync(key,d,TimeSpan.FromMinutes(5),ct); return d; } static decimal Variation(decimal current,decimal previous)=>previous==0?(current==0?0:100):Math.Round(((current-previous)/previous)*100,2);}
public class UpcomingDuesHandler(ITransactionRepository txRepo):IRequestHandler<UpcomingDuesQuery,List<UpcomingDueDto>>{public async Task<List<UpcomingDueDto>> Handle(UpcomingDuesQuery q,CancellationToken ct)=>(await txRepo.UpcomingDueAsync(q.UserId,q.Days<=0?7:q.Days)).Select(x=>x.ToUpcomingDueDto()).OrderBy(x=>x.DueDate).ToList();}
public class GetCategoryExpensesHandler(ITransactionRepository txRepo, ICategoryRepository catRepo): IRequestHandler<GetCategoryExpensesQuery,List<CategoryExpenseDto>>{ public async Task<List<CategoryExpenseDto>> Handle(GetCategoryExpensesQuery q,CancellationToken ct){var grouped=await txRepo.CategoryExpenseAsync(q.UserId,q.Month,q.Year); var cats=(await catRepo.GetByUserAsync(q.UserId)).ToDictionary(x=>x.Id,x=>x); var total=grouped.Sum(x=>x.Total); return grouped.Select(x=>{cats.TryGetValue(x.CategoryId,out var c); var p=total==0?0:Math.Round((x.Total/total)*100,2); return new CategoryExpenseDto(x.CategoryId,c?.Name??"N/A",c?.Color??"#94a3b8",x.Total,p);}).OrderByDescending(x=>x.Total).ToList(); }}
public class GetCashFlowHandler(ITransactionRepository txRepo): IRequestHandler<GetCashFlowQuery,List<CashFlowItemDto>>{ public async Task<List<CashFlowItemDto>> Handle(GetCashFlowQuery q,CancellationToken ct)=>(await txRepo.CashFlowAsync(q.UserId,q.Year)).Select(x=>new CashFlowItemDto(x.Month,x.Income,x.Expense,x.Income-x.Expense)).ToList(); }
