using System.Text.RegularExpressions;
using Aurora.Application.Interfaces;
using Aurora.Domain.Entities;
using Aurora.Domain.Enums;
using Aurora.Infrastructure.Mongo;
using MongoDB.Bson;
using MongoDB.Driver;
using StackExchange.Redis;

namespace Aurora.Infrastructure.Repositories;
public class RefreshTokenRepository(MongoContext c):IRefreshTokenRepository{
 public Task AddAsync(RefreshToken token)=>c.RefreshTokens.InsertOneAsync(token);
 public Task<RefreshToken?> GetByHashAsync(string hash)=>c.RefreshTokens.Find(x=>x.TokenHash==hash).FirstOrDefaultAsync();
 public async Task RevokeAsync(string id){var update=Builders<RefreshToken>.Update.Set(x=>x.IsRevoked,true).Set(x=>x.RevokedAt,DateTime.UtcNow); await c.RefreshTokens.UpdateOneAsync(x=>x.Id==id,update);}
 public async Task RevokeAllByUserAsync(string userId){var update=Builders<RefreshToken>.Update.Set(x=>x.IsRevoked,true).Set(x=>x.RevokedAt,DateTime.UtcNow); await c.RefreshTokens.UpdateManyAsync(x=>x.UserId==userId&&!x.IsRevoked,update);}
}
public class RedisRateLimiter(IConnectionMultiplexer redis):IRateLimiter{
 public async Task<bool> IsAllowedAsync(string key,int maxRequests,TimeSpan window){
  var db=redis.GetDatabase();
  var rlKey=$"rl:{key}";
  var count=await db.StringIncrementAsync(rlKey);
  if(count==1) await db.KeyExpireAsync(rlKey,window);
  return count<=maxRequests;
 }
}
public class UserRepository(MongoContext c):IUserRepository{public Task<User?> GetByEmailAsync(string email)=>c.Users.Find(x=>x.Email==email).FirstOrDefaultAsync(); public Task<User?> GetByIdAsync(string id)=>c.Users.Find(x=>x.Id==id).FirstOrDefaultAsync(); public Task AddAsync(User user)=>c.Users.InsertOneAsync(user); public Task UpdateAsync(User user){user.UpdatedAt=DateTime.UtcNow; return c.Users.ReplaceOneAsync(x=>x.Id==user.Id,user);}}
public class AccountRepository(MongoContext c):IAccountRepository{public Task<List<Account>> GetByUserAsync(string userId)=>c.Accounts.Find(x=>x.UserId==userId).ToListAsync(); public Task<Account?> GetByIdAsync(string id,string userId)=>c.Accounts.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(Account a)=>c.Accounts.InsertOneAsync(a); public Task UpdateAsync(Account a){a.UpdatedAt=DateTime.UtcNow; return c.Accounts.ReplaceOneAsync(x=>x.Id==a.Id&&x.UserId==a.UserId,a);} public Task DeleteAsync(string id,string userId)=>c.Accounts.DeleteOneAsync(x=>x.Id==id&&x.UserId==userId); public async Task<decimal> GetTotalBalanceAsync(string userId)=>(await c.Accounts.Find(x=>x.UserId==userId&&!x.IsArchived&&x.Type!=AccountType.CreditCard).ToListAsync()).Sum(x=>x.CurrentBalance);}
public class CategoryRepository(MongoContext c):ICategoryRepository{public Task<List<Category>> GetByUserAsync(string userId)=>c.Categories.Find(x=>x.UserId==userId).ToListAsync(); public Task<Category?> GetByIdAsync(string id,string userId)=>c.Categories.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(Category x)=>c.Categories.InsertOneAsync(x); public Task UpdateAsync(Category x){x.UpdatedAt=DateTime.UtcNow; return c.Categories.ReplaceOneAsync(a=>a.Id==x.Id&&a.UserId==x.UserId,x);} public Task DeleteAsync(string id,string userId)=>c.Categories.DeleteOneAsync(x=>x.Id==id&&x.UserId==userId);
public async Task SeedDefaultsAsync(string userId){ var i=new[]{"Salário","Freelance","Investimentos"}.Select(n=>new Category{UserId=userId,Name=n,Type=CategoryType.Income,IsDefault=true}); var e=new[]{"Moradia","Alimentação","Transporte","Saúde","Lazer","Educação","Assinaturas","Outros"}.Select(n=>new Category{UserId=userId,Name=n,Type=CategoryType.Expense,IsDefault=true}); await c.Categories.InsertManyAsync(i.Concat(e)); }}
public class TransactionRepository(MongoContext c):ITransactionRepository{
 public async Task<List<Transaction>> GetByFilterAsync(string userId,int? month,int? year,TransactionType? type,TransactionStatus? status,string? categoryId,string? accountId){ var filter=BuildFilter(new TransactionFilter(userId,month,year,type,status,categoryId,accountId)); return await c.Transactions.Find(filter).SortByDescending(x=>x.Date).ToListAsync(); }
 public async Task<(List<Transaction> Items,int TotalCount)> GetPagedAsync(TransactionFilter filter,int page,int pageSize){var mongoFilter=BuildFilter(filter); var totalLong=await c.Transactions.CountDocumentsAsync(mongoFilter); var skip=(page-1)*pageSize; var items=await c.Transactions.Find(mongoFilter).SortByDescending(x=>x.Date).Skip(skip).Limit(pageSize).ToListAsync(); return (items,(int)totalLong);}
 static FilterDefinition<Transaction> BuildFilter(TransactionFilter q){var b=Builders<Transaction>.Filter; var f=b.Eq(x=>x.UserId,q.UserId); if(q.DateFrom.HasValue||q.DateTo.HasValue){if(q.DateFrom.HasValue) f &= b.Gte(x=>x.Date,q.DateFrom.Value); if(q.DateTo.HasValue) f &= b.Lt(x=>x.Date,q.DateTo.Value.Date.AddDays(1));} else if(q.Month.HasValue&&q.Year.HasValue){var s=new DateTime(q.Year.Value,q.Month.Value,1); var e=s.AddMonths(1); f &= b.Gte(x=>x.Date,s) & b.Lt(x=>x.Date,e);} if(q.Type.HasValue) f &= b.Eq(x=>x.Type,q.Type); if(q.Status.HasValue) f &= b.Eq(x=>x.Status,q.Status); var accountIds=NormalizeIds(q.AccountIds,q.AccountId); if(accountIds.Count>0) f &= b.In(x=>x.AccountId,accountIds); var categoryIds=NormalizeIds(q.CategoryIds,q.CategoryId); if(categoryIds.Count>0) f &= b.In(x=>x.CategoryId,categoryIds); if(q.MinAmount.HasValue) f &= b.Gte(x=>x.Amount,q.MinAmount.Value); if(q.MaxAmount.HasValue) f &= b.Lte(x=>x.Amount,q.MaxAmount.Value); if(!string.IsNullOrWhiteSpace(q.Search)){var regex=new BsonRegularExpression(Regex.Escape(q.Search.Trim()),"i"); f &= b.Regex(x=>x.Description,regex);} return f;}
 static List<string> NormalizeIds(List<string>? many,string? single){var set=new HashSet<string>(StringComparer.Ordinal); if(many is not null) foreach(var id in many) if(!string.IsNullOrWhiteSpace(id)) set.Add(id.Trim()); if(!string.IsNullOrWhiteSpace(single)) set.Add(single.Trim()); return set.ToList();}
 public Task<Transaction?> GetByIdAsync(string id,string userId)=>c.Transactions.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(Transaction tx)=>c.Transactions.InsertOneAsync(tx); public Task UpdateAsync(Transaction tx){tx.UpdatedAt=DateTime.UtcNow; return c.Transactions.ReplaceOneAsync(x=>x.Id==tx.Id&&x.UserId==tx.UserId,tx);} public Task DeleteAsync(string id,string userId)=>c.Transactions.DeleteOneAsync(x=>x.Id==id&&x.UserId==userId);
 public Task<bool> ExistsByAccountIdAsync(string accountId,string userId)=>c.Transactions.Find(x=>x.AccountId==accountId&&x.UserId==userId).AnyAsync(); public Task<bool> ExistsByCategoryIdAsync(string categoryId,string userId)=>c.Transactions.Find(x=>x.CategoryId==categoryId&&x.UserId==userId).AnyAsync();
 public async Task<decimal> SumAsync(string userId,int month,int year,TransactionType type,TransactionStatus status){
  var start=new DateTime(year,month,1); var end=start.AddMonths(1);
  var f=Builders<Transaction>.Filter.Eq(x=>x.UserId,userId) & Builders<Transaction>.Filter.Gte(x=>x.Date,start) & Builders<Transaction>.Filter.Lt(x=>x.Date,end) & Builders<Transaction>.Filter.Eq(x=>x.Type,type) & Builders<Transaction>.Filter.Eq(x=>x.Status,status);
  var r=await c.Transactions.Aggregate().Match(f).Group(_=>1,g=>new { Total=g.Sum(x=>x.Amount)}).FirstOrDefaultAsync();
  return r?.Total ?? 0m;
 }
 public async Task<int> CountAsync(string userId,int month,int year,TransactionStatus status){
  var start=new DateTime(year,month,1); var end=start.AddMonths(1);
  var f=Builders<Transaction>.Filter.Eq(x=>x.UserId,userId) & Builders<Transaction>.Filter.Gte(x=>x.Date,start) & Builders<Transaction>.Filter.Lt(x=>x.Date,end) & Builders<Transaction>.Filter.Eq(x=>x.Status,status);
  return (int)await c.Transactions.CountDocumentsAsync(f);
 }
 public Task<List<Transaction>> RecentAsync(string userId,int limit=5)=>c.Transactions.Find(x=>x.UserId==userId).SortByDescending(x=>x.Date).Limit(limit).ToListAsync();
 public async Task<List<(string CategoryId, decimal Total)>> CategoryExpenseAsync(string userId,int month,int year)=>(await GetByFilterAsync(userId,month,year,TransactionType.Expense,TransactionStatus.Paid,null,null)).GroupBy(x=>x.CategoryId).Select(g=>(g.Key,g.Sum(x=>x.Amount))).ToList();
 public async Task<List<(int Month, decimal Income, decimal Expense)>> CashFlowAsync(string userId,int year){var list=new List<(int,decimal,decimal)>(); for(var m=1;m<=12;m++){var i=await SumAsync(userId,m,year,TransactionType.Income,TransactionStatus.Paid); var e=await SumAsync(userId,m,year,TransactionType.Expense,TransactionStatus.Paid); list.Add((m,i,e));} return list; }
 public Task<List<Transaction>> UpcomingDueAsync(string userId,int days){var today=DateTime.UtcNow.Date; var end=today.AddDays(Math.Max(1,days)); var statuses=new[]{TransactionStatus.Pending,TransactionStatus.Overdue}; var f=Builders<Transaction>.Filter.Eq(x=>x.UserId,userId)&Builders<Transaction>.Filter.Ne(x=>x.DueDate,null)&Builders<Transaction>.Filter.Lte(x=>x.DueDate,end)&Builders<Transaction>.Filter.In(x=>x.Status,statuses); return c.Transactions.Find(f).SortBy(x=>x.DueDate).ToListAsync();}
 public Task<List<Transaction>> GetByInvoiceIdAsync(string invoiceId,string userId)=>c.Transactions.Find(x=>x.UserId==userId&&x.CreditCardInvoiceId==invoiceId).SortByDescending(x=>x.Date).ToListAsync();
 public Task<List<Transaction>> GetByRecurrenceGroupAsync(Guid groupId,string userId)=>c.Transactions.Find(x=>x.UserId==userId&&x.RecurrenceGroupId==groupId).SortBy(x=>x.Date).ToListAsync();
}
public class FinancingRepository(MongoContext c):IFinancingRepository{public Task<List<Financing>> GetByUserAsync(string userId)=>c.Financings.Find(x=>x.UserId==userId).SortBy(x=>x.Name).ToListAsync(); public Task<Financing?> GetByIdAsync(string id,string userId)=>c.Financings.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(Financing f)=>c.Financings.InsertOneAsync(f); public Task UpdateAsync(Financing f){f.UpdatedAt=DateTime.UtcNow; return c.Financings.ReplaceOneAsync(x=>x.Id==f.Id&&x.UserId==f.UserId,f);} public Task DeleteAsync(string id,string userId)=>c.Financings.DeleteOneAsync(x=>x.Id==id&&x.UserId==userId);}
public class CreditCardInvoiceRepository(MongoContext c):ICreditCardInvoiceRepository{public Task<List<CreditCardInvoice>> GetByAccountAsync(string accountId,string userId)=>c.CreditCardInvoices.Find(x=>x.AccountId==accountId&&x.UserId==userId).SortByDescending(x=>x.Year).ThenByDescending(x=>x.Month).ToListAsync(); public Task<CreditCardInvoice?> GetByPeriodAsync(string accountId,string userId,int month,int year)=>c.CreditCardInvoices.Find(x=>x.AccountId==accountId&&x.UserId==userId&&x.Month==month&&x.Year==year).FirstOrDefaultAsync(); public Task<CreditCardInvoice?> GetByIdAsync(string id,string userId)=>c.CreditCardInvoices.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(CreditCardInvoice invoice)=>c.CreditCardInvoices.InsertOneAsync(invoice); public Task UpdateAsync(CreditCardInvoice invoice){invoice.UpdatedAt=DateTime.UtcNow; return c.CreditCardInvoices.ReplaceOneAsync(x=>x.Id==invoice.Id&&x.UserId==invoice.UserId,invoice);} public async Task<decimal> SumOpenByAccountAsync(string accountId,string userId){var f=Builders<CreditCardInvoice>.Filter.Eq(x=>x.AccountId,accountId)&Builders<CreditCardInvoice>.Filter.Eq(x=>x.UserId,userId)&Builders<CreditCardInvoice>.Filter.Ne(x=>x.Status,CreditCardInvoiceStatus.Paid); var r=await c.CreditCardInvoices.Aggregate().Match(f).Group(_=>1,g=>new { Total=g.Sum(x=>x.TotalAmount)}).FirstOrDefaultAsync(); return r?.Total??0m;}}
public class BudgetRepository(MongoContext c):IBudgetRepository{public Task<List<Budget>> GetByMonthAsync(string userId,int month,int year)=>c.Budgets.Find(x=>x.UserId==userId&&x.Month==month&&x.Year==year).ToListAsync(); public Task<Budget?> GetByCategoryPeriodAsync(string userId,string categoryId,int month,int year)=>c.Budgets.Find(x=>x.UserId==userId&&x.CategoryId==categoryId&&x.Month==month&&x.Year==year).FirstOrDefaultAsync(); public Task<Budget?> GetByIdAsync(string id,string userId)=>c.Budgets.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(Budget budget)=>c.Budgets.InsertOneAsync(budget); public Task UpdateAsync(Budget budget){budget.UpdatedAt=DateTime.UtcNow; return c.Budgets.ReplaceOneAsync(x=>x.Id==budget.Id&&x.UserId==budget.UserId,budget);} public Task DeleteAsync(string id,string userId)=>c.Budgets.DeleteOneAsync(x=>x.Id==id&&x.UserId==userId);}
public class TransferRepository(MongoContext c):ITransferRepository{public Task<List<Transfer>> GetByFilterAsync(string userId,int? month,int? year){var f=Builders<Transfer>.Filter.Eq(x=>x.UserId,userId); if(month.HasValue&&year.HasValue){var s=new DateTime(year.Value,month.Value,1); var e=s.AddMonths(1); f &= Builders<Transfer>.Filter.Gte(x=>x.Date,s)&Builders<Transfer>.Filter.Lt(x=>x.Date,e);} return c.Transfers.Find(f).SortByDescending(x=>x.Date).ToListAsync();} public Task<Transfer?> GetByIdAsync(string id,string userId)=>c.Transfers.Find(x=>x.Id==id&&x.UserId==userId).FirstOrDefaultAsync(); public Task AddAsync(Transfer transfer)=>c.Transfers.InsertOneAsync(transfer); public Task DeleteAsync(string id,string userId)=>c.Transfers.DeleteOneAsync(x=>x.Id==id&&x.UserId==userId);}
