using Aurora.Domain.Enums;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
namespace Aurora.Domain.Entities;
public abstract class EntityBase { [BsonId, BsonRepresentation(BsonType.ObjectId)] public string Id { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; }
public class User:EntityBase { public string Name { get; set; }=""; public string Email { get; set; }=""; public string PasswordHash { get; set; }=""; }
public class Account:EntityBase { public string UserId { get; set; }=""; public string Name { get; set; }=""; public AccountType Type { get; set; } public decimal InitialBalance { get; set; } public decimal CurrentBalance { get; set; } public string Color { get; set; }="#6366f1"; public bool IsArchived { get; set; } public decimal CreditLimit { get; set; } public int ClosingDay { get; set; }=10; public int DueDay { get; set; }=15; }
public class Category:EntityBase { public string UserId { get; set; }=""; public string Name { get; set; }=""; public CategoryType Type { get; set; } public string Color { get; set; }="#94a3b8"; public string Icon { get; set; }="tag"; public bool IsDefault { get; set; } }
public class Transaction:EntityBase { public string UserId { get; set; }=""; public string AccountId { get; set; }=""; public string CategoryId { get; set; }=""; public string Description { get; set; }=""; public decimal Amount { get; set; } public TransactionType Type { get; set; } public TransactionStatus Status { get; set; } public DateTime Date { get; set; } public DateTime? DueDate { get; set; } public string? Notes { get; set; } public string? CreditCardInvoiceId { get; set; } public bool IsRecurring { get; set; } public RecurrenceType? RecurrenceType { get; set; } public int RecurrenceInterval { get; set; }=1; public DateTime? RecurrenceEndDate { get; set; } public Guid? RecurrenceGroupId { get; set; } public int? RecurrenceIndex { get; set; } public int? TotalInstallments { get; set; } }
public class CreditCardInvoice:EntityBase { public string UserId { get; set; }=""; public string AccountId { get; set; }=""; public int Month { get; set; } public int Year { get; set; } public decimal TotalAmount { get; set; } public CreditCardInvoiceStatus Status { get; set; }=CreditCardInvoiceStatus.Open; public DateTime DueDate { get; set; } public DateTime? PaidAt { get; set; } }
public class Budget:EntityBase { public string UserId { get; set; }=""; public string CategoryId { get; set; }=""; public int Month { get; set; } public int Year { get; set; } public decimal LimitAmount { get; set; } }
public class Transfer:EntityBase { public string UserId { get; set; }=""; public string FromAccountId { get; set; }=""; public string ToAccountId { get; set; }=""; public decimal Amount { get; set; } public DateTime Date { get; set; } public string Description { get; set; }=""; public TransferStatus Status { get; set; }=TransferStatus.Completed; }
public class FinancingInstallment { public int Number { get; set; } public DateTime DueDate { get; set; } public decimal OpeningBalance { get; set; } public decimal Amortization { get; set; } public decimal Interest { get; set; } public decimal Insurance { get; set; } public decimal Fees { get; set; } public decimal TotalPayment { get; set; } public decimal ClosingBalance { get; set; } public FinancingInstallmentStatus Status { get; set; } public DateTime? PaidAt { get; set; } public decimal? PaidAmount { get; set; } public string? LinkedTransactionId { get; set; } }
public class RefreshToken { [BsonId, BsonRepresentation(BsonType.ObjectId)] public string Id { get; set; }=string.Empty; public string TokenHash { get; set; }=""; public string UserId { get; set; }=""; public DateTime ExpiresAt { get; set; } public DateTime CreatedAt { get; set; }=DateTime.UtcNow; public DateTime? RevokedAt { get; set; } public bool IsRevoked { get; set; } }
public class Financing:EntityBase { public string UserId { get; set; }=""; public string Name { get; set; }=""; public FinancingType Type { get; set; } public AmortizationSystem AmortizationSystem { get; set; } public FinancingStatus Status { get; set; }=FinancingStatus.Active; public string Institution { get; set; }=""; public decimal AssetValue { get; set; } public decimal DownPayment { get; set; } public decimal FinancedAmount { get; set; } public decimal AnnualInterestRate { get; set; } public decimal MonthlyInsurance { get; set; } public decimal MonthlyFees { get; set; } public decimal? CetAnnualRate { get; set; } public int TermMonths { get; set; } public DateTime FirstDueDate { get; set; } public List<FinancingInstallment> Installments { get; set; }=[]; public string? LinkedAccountId { get; set; } public string? Notes { get; set; } public string? PropertyAddress { get; set; } public string? PropertyRegistration { get; set; } public string? VehicleBrand { get; set; } public string? VehicleModel { get; set; } public int? VehicleYear { get; set; } public string? VehiclePlate { get; set; } }
